### ISSUE TITLE
dL_df bug?

### ISSUE THREAD

**Issue by jpober** [steven-murray/21cmSense#41]
I was looking for a reference implementation of this calculation and so happened to take a peek here -- and I think (1+z) is supposed to be squared?  Compare with dRpara_df here: https://github.com/HERA-Team/hera_pspec/blob/master/hera_pspec/conversions.py

**Comment by plaplant** [comment]
Don't mean to poke my head into this issue, but looking at the current `master` branch, it seems like the change from #43 (which was closed without merging) is somehow in the code base:

https://github.com/steven-murray/21cmSense/blob/8464956b720c9dd7079711512828d7f3947854c3/py21cmsense/conversions.py#L71-L82

Maybe something got messed up in a rebase somewhere? Regardless, I think the `(1 + z)` should *not* be squared (because as was noted in #43, there's effectively another factor coming from `z2f`).

**Comment by steven-murray** [comment]
Oh shoot -- nice pickup! Fixing in that above PR.
